In [1]:
import pandas as pd
from datetime import datetime
import numpy as np

In [59]:
df=pd.read_csv('C:/Users/1/Downloads/hh.zip')
df

,data_source,v_id,id,date_published,is_open,name,description,salary_from,salary_to,salary_currency,...,region_id,region_name,region_district_id,region_district_name,role_id,role_name,skills,hard_skills,soft_skills,experience_category
0,superjob,002c181d-02ff-bc9c-0a61-84f51501f72a,ddc0e7a2-3fb9-11ed-a9b7-dbfed3997e57,2023-10-09,1,Инженер по пусконаладке станков / Сервисный ин...,Наладка и проведение испытаний балансировочных...,80000,100000,RUB,...,347,Москва,1,Центральный,0,Инженер по пусконаладке станков / Сервисный ин...,NaN,NaN,NaN,1-3 года
1,superjob,00efeefa-3424-b47d-d29f-ca7baca22653,95e44fd0-3d06-11ee-b683-dbfed3997e57,2023-09-09,1,Инженер (2 категории),Обязанности:- Монтаж/демонтаж систем широкопол...,60000,120000,RUB,...,578,Ханты-Мансийский АО - Югра,5,Уральский,0,Инженер (2 категории),NaN,NaN,NaN,1-3 года
2,superjob,01202c78-e3e4-4d4a-f42d-001fdd73ed51,17600752-d468-11ed-b282-dbfed3997e57,2023-08-31,0,Начальник кабинета автоматизированных систем у...,Условия: Поликлиника находится в историческом...,100000,100000,RUB,...,475,Санкт-Петербург,2,Северо-Западный,0,Начальник кабинета автоматизированных систем у...,NaN,NaN,NaN,1-3 года
3,superjob,0130559c-07d5-c042-80ca-722d4441df74,1d435c52-964f-11ed-a841-dbfed3997e57,2023-03-18,0,Senior 1С программист,Роль в компании: Доработка нового функционала ...,200000,200000,RUB,...,347,Москва,1,Центральный,0,Senior 1С программист,NaN,NaN,NaN,1-3 года
4,superjob,013f14be-f59f-5d61-4627-60dfb324ea2b,d026f352-4b94-11ed-8804-dbfed3997e57,2023-07-13,0,Инженер связи,Обязанности:. Эксплуатация и настройка внутрен...,0,0,RUB,...,347,Москва,1,Центральный,0,Инженер связи,NaN,NaN,NaN,1-3 года
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149805,hh,fcc133d7-318b-2dec-3743-cb4df8f7768c,79108952,2023-10-04,0,Кладовщик / грузчик / работник склада,Обязанности: - Прием и выдача товара в произ...,45000,50000,RUB,...,347,Москва,1,Центральный,31,Грузчик,выполнение производственного технического конт...,выполнение производственного технического конт...,NaN,Без опыта
149806,hh,fcc14044-f216-3dd5-8521-380f8c43315d,73894723,2022-12-16,0,Руководитель астрологического направления для B2B,Привет! Мы в брендинговом агентстве ENDY ищем...,0,0,RUB,...,475,Санкт-Петербург,2,Северо-Западный,40,Другое,"коммуникативная грамотность, базовая инструмен...",NaN,"коммуникативная грамотность, базовая инструмен...",1-3 года
149807,hh,fcc14f03-01b7-fe76-1746-092bd783db6d,74274777,2022-12-26,0,Мерчендайзер Стационарный,ДатаМаркетинг - крупнейшая компания в сфере FM...,2000,0,RUB,...,347,Москва,1,Центральный,77,Мерчандайзер,мерчандайзинг,мерчандайзинг,NaN,Без опыта
149808,hh,fcc1ba08-bea8-66cc-b9d2-d5f2b3d4cf34,79853966,2023-04-27,0,Печатник,ТОО &quot;ALA Sintez&quot; производит набор пе...,41342,0,RUB,...,26,Алматы,0,NaN,40,Другое,NaN,NaN,NaN,1-3 года
149809,hh,fcc1d307-2507-9a3f-0e33-5d308d9fcb4f,72731676,2022-04-12,0,Офис-менеджер / Помощник руководителя,"Мы hate.agency — digital агентство, входящее в...",60000,70000,RUB,...,347,Москва,1,Центральный,88,Офис-менеджер,"microsoft excel, microsoft word, базовая инстр...","microsoft excel, microsoft word, базовые знани...","базовая инструментальная грамотность, коммуник...",1-3 года

Фильтруем от нулевых зарплат

In [60]:
df_cleaned = df[~((df['salary_from'] == 0) & (df['salary_to'] == 0))]

df_cleaned

,data_source,v_id,id,date_published,is_open,name,description,salary_from,salary_to,salary_currency,...,region_id,region_name,region_district_id,region_district_name,role_id,role_name,skills,hard_skills,soft_skills,experience_category
0,superjob,002c181d-02ff-bc9c-0a61-84f51501f72a,ddc0e7a2-3fb9-11ed-a9b7-dbfed3997e57,2023-10-09,1,Инженер по пусконаладке станков / Сервисный ин...,Наладка и проведение испытаний балансировочных...,80000,100000,RUB,...,347,Москва,1,Центральный,0,Инженер по пусконаладке станков / Сервисный ин...,NaN,NaN,NaN,1-3 года
1,superjob,00efeefa-3424-b47d-d29f-ca7baca22653,95e44fd0-3d06-11ee-b683-dbfed3997e57,2023-09-09,1,Инженер (2 категории),Обязанности:- Монтаж/демонтаж систем широкопол...,60000,120000,RUB,...,578,Ханты-Мансийский АО - Югра,5,Уральский,0,Инженер (2 категории),NaN,NaN,NaN,1-3 года
2,superjob,01202c78-e3e4-4d4a-f42d-001fdd73ed51,17600752-d468-11ed-b282-dbfed3997e57,2023-08-31,0,Начальник кабинета автоматизированных систем у...,Условия: Поликлиника находится в историческом...,100000,100000,RUB,...,475,Санкт-Петербург,2,Северо-Западный,0,Начальник кабинета автоматизированных систем у...,NaN,NaN,NaN,1-3 года
3,superjob,0130559c-07d5-c042-80ca-722d4441df74,1d435c52-964f-11ed-a841-dbfed3997e57,2023-03-18,0,Senior 1С программист,Роль в компании: Доработка нового функционала ...,200000,200000,RUB,...,347,Москва,1,Центральный,0,Senior 1С программист,NaN,NaN,NaN,1-3 года
5,superjob,01ee16f7-bec2-f62c-c420-c9b43bd55e35,f7d763f1-051e-11ee-81f4-dbfed3997e57,2023-07-30,0,Поведенческий аналитик/педагог (АВА-терапист/д...,Индивидуальная работа с детьми с ОВЗ (главным ...,30000,60000,RUB,...,371,Новосибирская область,6,Сибирский,0,Поведенческий аналитик/педагог (АВА-терапист/д...,NaN,NaN,NaN,Без опыта
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149803,hh,fcc019bd-c87b-1cf2-fdba-3e76d1cb8045,77865503,2023-10-03,0,Программист микроконтроллеров (инженер-разрабо...,Обязанности: разработка программного обеспече...,70000,0,RUB,...,475,Санкт-Петербург,2,Северо-Западный,96,"Программист, разработчик",NaN,NaN,NaN,Более 3 лет
149805,hh,fcc133d7-318b-2dec-3743-cb4df8f7768c,79108952,2023-10-04,0,Кладовщик / грузчик / работник склада,Обязанности: - Прием и выдача товара в произ...,45000,50000,RUB,...,347,Москва,1,Центральный,31,Грузчик,выполнение производственного технического конт...,выполнение производственного технического конт...,NaN,Без опыта
149807,hh,fcc14f03-01b7-fe76-1746-092bd783db6d,74274777,2022-12-26,0,Мерчендайзер Стационарный,ДатаМаркетинг - крупнейшая компания в сфере FM...,2000,0,RUB,...,347,Москва,1,Центральный,77,Мерчандайзер,мерчандайзинг,мерчандайзинг,NaN,Без опыта
149808,hh,fcc1ba08-bea8-66cc-b9d2-d5f2b3d4cf34,79853966,2023-04-27,0,Печатник,ТОО &quot;ALA Sintez&quot; производит набор пе...,41342,0,RUB,...,26,Алматы,0,NaN,40,Другое,NaN,NaN,NaN,1-3 года
149809,hh,fcc1d307-2507-9a3f-0e33-5d308d9fcb4f,72731676,2022-04-12,0,Офис-менеджер / Помощник руководителя,"Мы hate.agency — digital агентство, входящее в...",60000,70000,RUB,...,347,Москва,1,Центральный,88,Офис-менеджер,"microsoft excel, microsoft word, базовая инстр...","microsoft excel, microsoft word, базовые знани...","базовая инструментальная грамотность, коммуник...",1-3 года

борьба с выбросами

In [133]:
import pandas as pd
import numpy as np

def clean_and_filter_salaries_3(df):
    # Поверхностная фильтрация
    df_clean = df[
        (df['salary_to'] <= 2_000_000)].copy()
    
    
    def filter_group(group):
        # Отдельно сохраняем строки, где зарплата == 0
        zeros = group[(group['salary_from'] == 0) | (group['salary_to'] == 0)]
        non_zeros = group[(group['salary_from'] != 0) & (group['salary_to'] != 0)]
        # Для редких вакансий 
        if len(non_zeros) < 20:
            filtered = non_zeros[
                (non_zeros['salary_from'] >= 10_000) & 
                (non_zeros['salary_to'] <= 1_000_000)
            ]
        else: # Для остальных вакансий
            q1_from, q3_from = non_zeros['salary_from'].quantile([0.04, 0.96])
            q1_to, q3_to = non_zeros['salary_to'].quantile([0.04, 0.96])
            iqr_from = q3_from - q1_from
            iqr_to = q3_to - q1_to
            lower_bound_from = q1_from - 1.5 * iqr_from
            upper_bound_from = q3_from + 1.5 * iqr_from
            lower_bound_to = q1_to - 1.5 * iqr_to
            upper_bound_to = q3_to + 1.5 * iqr_to
            
            filtered = non_zeros[
                (non_zeros['salary_from'] >= lower_bound_from) & 
                (non_zeros['salary_from'] <= upper_bound_from) &
                (non_zeros['salary_to'] >= lower_bound_to) & 
                (non_zeros['salary_to'] <= upper_bound_to)
            ]

        # Объединяем отфильтрованные и нулевые строки
        return pd.concat([filtered, zeros], ignore_index=True)

    df_filtered = df_clean.groupby('role_name', group_keys=False).apply(filter_group)

    #  СПЕЦИАЛЬНЫЕ ПРАВИЛА ДЛЯ ОТДЕЛЬНЫХ ПРОФЕССИЙ 
    # Расширяем границы для стажёровок и подработки
    intern_mask = df_filtered['role_name'].str.contains(
        'Стажёр|Intern|Подработка|подработка|ПОДРАБОТКА',
        case=False,
        na=False
    )
    df_filtered.loc[intern_mask, 'salary_from'] = df_filtered.loc[intern_mask, 'salary_from'].clip(lower=5_000)
     # Расширяем границы для топ-менеджеров
    executive_mask = df_filtered['role_name'].str.contains(
        r'\b(CEO|CTO|Директор|Генеральный директор|Head of)\b',
        case=False,
        na=False
    )
    df_filtered.loc[executive_mask, 'salary_to'] = df_filtered.loc[executive_mask, 'salary_to'].clip(upper=2_000_000)


    return df_filtered

In [135]:
df_clean_1=clean_and_filter_salaries_3(df_cleaned)
df_clean_1

C:\Users\1\AppData\Local\Temp\ipykernel_19388\2759236101.py:40: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_filtered = df_clean.groupby('role_name', group_keys=False).apply(filter_group)
C:\Users\1\AppData\Local\Temp\ipykernel_19388\2759236101.py:51: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  executive_mask = df_filtered['role_name'].str.contains(

,data_source,v_id,id,date_published,is_open,name,description,salary_from,salary_to,salary_currency,...,region_id,region_name,region_district_id,region_district_name,role_id,role_name,skills,hard_skills,soft_skills,experience_category
0,rvr,47555172-110f-005d-a7b3-2f1abc6f996c,a40b03d0-433f-11ee-9064-dd0276383d19,2023-08-28,1,1C Аналитик,Сбор и формализация требований заказчика; Анал...,100000,250000,RUB,...,347,Москва,1,Центральный,0,1C Аналитик,предприятие управление производственным предпр...,предприятие управление производственным предпр...,NaN,Более 3 лет
0,rabotaru,ec06770f-ebee-6da6-fa31-fcbee1ea8a11,9357ac01-2af3-11ee-8d6f-dbfed3997e57,2023-07-25,0,1С Программист / Разработчик(удаленно),Вакансия компании: 839Обязанности:Участие в пр...,80000,120000,RUB,...,347,Москва,1,Центральный,0,1С Программист / Разработчик(удаленно),NaN,NaN,NaN,Более 3 лет
0,rabotaru,2ba55ea2-1a66-ad03-b52b-7b2d5e38775a,7bd6b233-4d7e-11ee-94b3-dbfed3997e57,2023-07-09,1,3D Визуализатор интерьеров,Вакансия компании: Design MarketДАННАЯ ВАКАНСИ...,80000,0,RUB,...,433,Республика Крым,3,Южный,0,3D Визуализатор интерьеров,NaN,NaN,NaN,Более 3 лет
0,rvr,322066d1-6f21-216f-21a8-f33ff99d9482,1b18f8c0-c3e2-11ed-99e0-17f530626801,2023-03-17,0,Android-разработчик,расширять функциональность социальной сети для...,25000,0,RUB,...,347,Москва,1,Центральный,0,Android-разработчик,NaN,NaN,NaN,1-3 года
0,hh,a5150a99-64fc-1636-263e-445d2dd7903b,74314554,2023-08-01,0,Специалист по работе с базами данных / BI-анал...,ВЦИОМ — ИССЛЕДОВАТЕЛЬСКИЙ ЦЕНТР №1 В РОССИИ И ...,60000,70000,RUB,...,485,Свердловская область,5,Уральский,156,"BI-аналитик, аналитик данных","microsoft power bi, python, ibm spss statistic...","microsoft power bi, python, ibm spss statistic...",NaN,1-3 года
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,rvr,5ce761f9-fa7d-21ca-489f-60781d5d3643,bf5928b5-dbf3-11ec-b20f-d768660431c4,2023-09-27,1,эксперт отдела связи,Выполнение работ по обеспечению бесперебойной ...,0,40000,RUB,...,348,Московская область,1,Центральный,0,эксперт отдела связи,NaN,NaN,NaN,1-3 года
0,rvr,b656b900-7e8f-5846-01e2-a2b1a0e42863,7320f535-4e3f-11ee-bbad-0d972cff014f,2023-09-26,1,электромеханик телевидения,- техническое обслуживание электроустановок; -...,40000,40000,RUB,...,111,Владимирская область,1,Центральный,0,электромеханик телевидения,NaN,NaN,NaN,Без опыта
1,rvr,2cde4395-937e-e39a-2310-5b1daeeae275,fb5b7215-d20f-11ed-8e1b-17f530626801,2023-01-09,1,электромеханик телевидения,"Обеспечение технической эксплуатации, обслужив...",26000,28000,RUB,...,552,Тюменская область,5,Уральский,0,электромеханик телевидения,NaN,NaN,NaN,1-3 года
0,rvr,428787b7-1ea5-c678-f3a3-feff1a9ed580,598a7452-07e3-11ed-9c09-dbfed3997e57,2023-09-15,1,электромонтер по эксплуатации электросчетчиков,"Установка/замена/проверка приборов учета ээ, ...",28000,28000,RUB,...,598,Челябинская область,5,Уральский,0,электромонтер по эксплуатации электросчетчиков,NaN,NaN,NaN,1-3 года
0,rvr,f852b705-53e2-688c-f422-7e37cf42aaf0,a064c465-2c23-11ee-a626-dd0276383d19,2023-07-28,0,юрист,Осуществляет постоянное взаимодействие и подде...,28000,30000,RUB,...,410,Приморский край,7,Дальневосточный,0,юрист,NaN,NaN,NaN,Без опыта

1 пункт анализа

In [ ]:
 Отдельно считаем медиану по ненулевым salary_from и salary_to, и сортируем по убыванию по salary_to

In [137]:
# Функция для вычисления медианы, игнорируя нулевые значения
def median_nonzero(series):
    nonzero = series[series != 0]
    if len(nonzero) == 0:
        return np.nan
    return nonzero.median()

grouped_1 = df_clean_1.groupby('role_name').agg(
    salary_from = ('salary_from', median_nonzero),
    salary_to = ('salary_to', median_nonzero),
    id_count = ('id', 'count')
).reset_index()


grouped = grouped_1.sort_values(by='salary_to', ascending=False)

grouped.head(10)

,role_name,salary_from,salary_to,id_count
3926,вице-президент,420000.0,480000.0,1
2810,Руководитель проектного офиса,400000.0,400000.0,1
68,Агент по продаже недвижимости,150000.0,350000.0,1
2938,Системный аналитик (сеньор),300000.0,350000.0,1
2786,Руководитель отдела разработки видеорешений,200000.0,350000.0,1
2688,Риэлтор,150000.0,325000.0,2
737,Дата инженер,250000.0,300000.0,1
824,Заместитель директора по ИТ по развитию навига...,300000.0,300000.0,1
825,Заместитель директора по ИТ по развитию систем...,300000.0,300000.0,1
35,Middle/senior PHP-программист (проекты электро...,170000.0,300000.0,1

Кривая вилка

In [140]:
trash=grouped[grouped['salary_to']<grouped['salary_from']]
trash

,role_name,salary_from,salary_to,id_count
591,"Главный врач, заведующий отделением",200000.0,150000.0,7
585,Геолог,100000.0,90000.0,47
767,Дизайнер одежды,100000.0,90000.0,3
2816,Руководитель проектов в области информационных...,95000.0,80000.0,10
3765,"Финансовый аналитик, инвестиционный аналитик",110000.0,80000.0,25
...,...,...,...,...
3874,аналитик,38121.0,18000.0,2
4202,начальник отделения связи,22757.0,17690.0,3
2582,Программист 1 С,63500.0,17000.0,2
2246,Начальник отделения связи,19350.0,16242.0,4
3306,Специалист по приему и обработке экстренных вы...,17460.5,16242.0,3

Отдельно считаем медиану по ненулевым salary_from и salary_to, считаем медиану по этим медианам и сортируем по убыванию

In [142]:
def median_of_two(row):
    if row['salary_from'] != 0 and row['salary_to'] != 0:
        return np.median([row['salary_from'], row['salary_to']])
    else:
        return np.nan

# Создаем новый столбец с медианой из двух зарплат
df_clean_1['salary_median'] = df_clean_1.apply(median_of_two, axis=1)

# Группируем и считаем медиану по этому новому столбцу
grouped = df_clean_1.groupby('role_name').agg(
    salary_median=('salary_median', 'median'),
    id_count=('id', 'count')
).reset_index()

# Сортируем по медиане зарплаты
grouped_sorted = grouped.sort_values(by='salary_median', ascending=False)

# Выводим топ-10
grouped_sorted.head(10)

,role_name,salary_median,id_count
3926,вице-президент,450000.0,1
2810,Руководитель проектного офиса,400000.0,1
2938,Системный аналитик (сеньор),325000.0,1
825,Заместитель директора по ИТ по развитию систем...,300000.0,1
824,Заместитель директора по ИТ по развитию навига...,300000.0,1
737,Дата инженер,275000.0,1
2786,Руководитель отдела разработки видеорешений,275000.0,1
201,Ведущий владелец продукта,250000.0,1
3730,Тимлид эксплуатации (ИТ инфраструктура),250000.0,1
2585,Программист 1C ERP,250000.0,1

Функция

In [144]:
import pandas as pd
import re
from typing import Optional, Tuple, Union

def calculate_median_salaries(
    df: pd.DataFrame,
    professions: list[str],
    experience: str | None = None,
    regions: list[str] | None = None,
    employment_types: list[str] | None = None,
    is_open: bool | None = None,
) -> tuple[float, float] | None:

    
    filtered_df = df.copy()
    
    # 1. Фильтрация по специальности
    if professions:
        profession_regex = "|".join([re.escape(p) for p in professions])
        mask = (
            filtered_df["name"].str.contains(profession_regex, case=False, na=False, regex=True) |
            filtered_df["role_name"].str.contains(profession_regex, case=False, na=False, regex=True)
        )
        filtered_df = filtered_df[mask]
    
    # 2. Фильтрация по опыту работы
    if experience:
        filtered_df = filtered_df[filtered_df["experience"] == experience]
    
    # 3. Фильтрация по регионам
    if regions:
        filtered_df = filtered_df[filtered_df["region_name"].isin(regions)]
    
    # 4. Фильтрация по типу занятости
    if employment_types:
        filtered_df = filtered_df[filtered_df["employment_label"].isin(employment_types)]
    
    # 5. Фильтрация по статусу вакансии
    if is_open is not None:
        filtered_df = filtered_df[filtered_df["is_open"] == int(is_open)]
    
    # 6. Фильтрация положительных зарплат
    filtered_df = filtered_df[
        (filtered_df["salary_from"] > 0) & 
        (filtered_df["salary_to"] > 0)
    ]
    
    # Отладочная информация
    print(f"Найдено вакансий после всех фильтров: {len(filtered_df)}")
    if not filtered_df.empty:
        print("Примеры вакансий:")
        print(filtered_df[["name", "salary_from", "salary_to", "region_name", "is_open"]].head())
    
    if filtered_df.empty:
        return None
    
    # Расчет медиан только для положительных значений
    median_from = filtered_df["salary_from"].median()
    median_to = filtered_df["salary_to"].median()
    
    return (median_from, median_to)

In [146]:
result = calculate_median_salaries(
    df=df_clean_1,
    professions=['Программист 1С'],
    experience="1-3",
    regions=["Москва"],
    employment_types=["Полная занятость"],
    is_open=False
)

if result:
    median_from, median_to = result
    print(f"Медиана salary_from: {median_from:.2f} руб.")
    print(f"Медиана salary_to: {median_to:.2f} руб.")
else:
    print("Подходящих вакансий с положительными зарплатами не найдено")

Найдено вакансий после всех фильтров: 8
Примеры вакансий:
                                                  name  salary_from  \
0    Ведущий программист 1С отдела разработки и вне...       165000
1                               Инженер-программист 1С        70000
0                                       Программист 1С       150000
310                                     Программист 1С       180000
381                                     Программист 1С       120000

     salary_to region_name  is_open
0       165000      Москва        0
1        70000      Москва        0
0       200000      Москва        0
310     230000      Москва        0
381     210000      Москва        0
Медиана salary_from: 120000.00 руб.
Медиана salary_to: 157500.00 руб.